name: Daily Standup

on:
  schedule:
    # 8 AM Pacific Time (9 AM during daylight saving time)
    # Run every 15 minutes on weekdays for 2 hours
    - cron: "0 16 * * 1-5"
    - cron: "15 16 * * 1-5"
    - cron: "30 16 * * 1-5"
    - cron: "45 16 * * 1-5"
    - cron: "0 17 * * 1-5"
    - cron: "15 17 * * 1-5"
    - cron: "30 17 * * 1-5"
    - cron: "45 17 * * 1-5"
    - cron: "0 18 * * 1-5"
  workflow_dispatch:

jobs:
  standup:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run standup service
        run: npm run start
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USER: ${{ secrets.SLACK_USER }}
          BOT_USER: ${{ secrets.BOT_USER }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
